[package]
name = "rustcraft"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.29"
wgpu = "0.19"
pollster = "0.3"
bytemuck = { version = "1.4", features = ["derive"] }
anyhow = "1.0"
cgmath = "0.18"
noise = "0.9"
env_logger = "0.10"
rayon = "1.8"
