[texture]
name = "Bedrock"
description = "Very dark, indestructible bedrock pattern"
size = [16, 16]

[palette]
"." = "#2A2A2A"  # Base dark gray (42, 42, 42)
"," = "#3E3E3E"  # Light dark gray (62, 62, 62)
":" = "#161616"  # Very dark gray (22, 22, 22)
"*" = "#4A4A4A"  # Brightest dark gray (74, 74, 74)
"#" = "#0A0A0A"  # Nearly black (10, 10, 10)

[pixels]
data = '''
*,:.#*,:##,:,*:.
,:*,.:#..,*,.:.*
.#,*,:.,*,*,:.,#
*,:##,*,:..*,:.,
,.:*.*:#*,:.*.,#
.#,*,:.,:,*,:.,#
#,:..,*,:..*,*:.
,*,.,:*.,*,.:,**
.#,*,:.,:,*,:.,#
*,:##,*,:..*,:.,
,.:*.*:#*,:.*.,#
.#,*,:.,:,*,:.,#
#,:..,*,:..*,*:.
,*,.,:*.,*,.:,**
.#,*,:.,:,*,:.,#
*,:##,*,:..*,:.,
'''