[texture]
name = "Cobblestone"
description = "Rough stone blocks fitted together"
size = [16, 16]

[palette]
"." = "#7A7A7A"  # Base gray stone (122, 122, 122)
"," = "#8E8E8E"  # Light gray stone (142, 142, 142)
":" = "#666666"  # Dark gray stone (102, 102, 102)
"*" = "#969696"  # Bright gray stone (150, 150, 150)
"#" = "#525252"  # Very dark gray stone (82, 82, 82)
"|" = "#3E3E3E"  # Mortar lines (62, 62, 62)

[pixels]
data = '''
*,:.||*,:||,:,*:
,:*,.|##.|*,.:.*
||||||||||||||||
*,:..,*,:..*,:.,
,.:*.#|#*|:.*.,#
||||||||||||||||
#,:..,*,:..*,*:.
,*,.,:*.|*,.|,**
||||||||||||||||
*,:..,*,:..*,:.,
,.:*.#|#*|:.*.,#
||||||||||||||||
#,:..,*,:..*,*:.
,*,.,:*.|*,.|,**
||||||||||||||||
*,:..,*,:..*,:.,
'''