[texture]
name = "Dirt"
description = "Brown earthy dirt block"
size = [16, 16]

[palette]
"." = "#8B5A2B"  # Base brown (139, 90, 43)
"," = "#A0632D"  # Light brown (160, 99, 45)
":" = "#6D4423"  # Dark brown (109, 68, 35)
"*" = "#996633"  # Medium brown (153, 102, 51)
"#" = "#5D3A1A"  # Very dark brown (93, 58, 26)

[pixels]
data = '''
*,:..,.,:..,*,:.
,:*,.:#.,*,.,:.*
.#,*,:.,:,*,:.,#
*,:..,.,:..,*,:.
,.:*.*:#*,:.*.,#
.#,*,:.,:,*,:.,#
#,:..,*,:..,.,:.
,*,.,:*.,*,.:,**
.#,*,:.,:,*,:.,#
*,:..,.,:..,*,:.
,.:*.*:#*,:.*.,#
.#,*,:.,:,*,:.,#
#,:..,*,:..,.,:.
,*,.,:*.,*,.:,**
.#,*,:.,:,*,:.,#
*,:..,.,:..,*,:.
'''