[texture]
name = "Glass"
description = "Glass with light blue tint"
size = [16, 16]

[palette]
"." = "#E0F0FF"  # Light blue (224, 240, 255)
"," = "#F0F8FF"  # Very light blue (240, 248, 255)
":" = "#D0E8FF"  # Medium blue (208, 232, 255)
"*" = "#F8FCFF"  # Almost white (248, 252, 255)
"#" = "#C0E0FF"  # Blue tint (192, 224, 255)

[pixels]
data = '''
*,:..*,:..,:,*:.
,:*,.:##.,*,.:.*
.#,*,:.,*,*,:.,#
*,:..,*,:..*,:.,
,.:*.*:#*,:.*.,#
.#,*,:.,:,*,:.,#
#,:..,*,:..*,*:.
,*,.,:*.,*,.:,**
.#,*,:.,:,*,:.,#
*,:..,*,:..*,:.,
,.:*.*:#*,:.*.,#
.#,*,:.,:,*,:.,#
#,:..,*,:..*,*:.
,*,.,:*.,*,.:,**
.#,*,:.,:,*,:.,#
*,:..,*,:..*,:.,
'''