[texture]
name = "Glass"
description = "Glass with light blue tint"
size = [16, 16]

[palette]
"." = "#E0F0FF80"  # Light blue (224, 240, 255, 128) - 50% opacity
"," = "#F0F8FF99"  # Very light blue (240, 248, 255, 153) - 60% opacity
":" = "#D0E8FF66"  # Medium blue (208, 232, 255, 102) - 40% opacity
"*" = "#F8FCFFB3"  # Almost white (248, 252, 255, 179) - 70% opacity
"#" = "#C0E0FF4D"  # Blue tint (192, 224, 255, 77) - 30% opacity

[pixels]
data = '''
*,:..*,:..,:,*:.
,:*,.:##.,*,.:.*
.#,*,:.,*,*,:.,#
*,:..,*,:..*,:.,
,.:*.*:#*,:.*.,#
.#,*,:.,:,*,:.,#
#,:..,*,:..*,*:.
,*,.,:*.,*,.:,**
.#,*,:.,:,*,:.,#
*,:..,*,:..*,:.,
,.:*.*:#*,:.*.,#
.#,*,:.,:,*,:.,#
#,:..,*,:..*,*:.
,*,.,:*.,*,.:,**
.#,*,:.,:,*,:.,#
*,:..,*,:..*,:.,
'''