[texture]
name = "Grass Side"
description = "Side face of grass blocks - green on top, dirt below"
size = [16, 16]

[palette]
"." = "#4A7C2A"  # Green (74, 124, 42)
"," = "#54872F"  # Light green (84, 135, 47) - reduced from 92,156,58
":" = "#406C22"  # Dark green (64, 108, 34) - increased from 58,92,26
"*" = "#5A9536"  # Bright green (90, 149, 54) - reduced from 106,170,74
"d" = "#8B5A2B"  # Dirt brown (139, 90, 43)
"b" = "#955D2A"  # Light dirt brown (149, 93, 42) - reduced contrast
"e" = "#7A5028"  # Dark dirt brown (122, 80, 40) - increased from 109,68,35
"f" = "#906030"  # Medium dirt brown (144, 96, 48) - reduced contrast

[pixels]
data = '''
*,:..*,:..,:,*:.
,:*,.:..,*,.:,.*
.e,*,:.,*,*,:.,e
*,:..,*,:bd*,:.,
,.:*.d:b*,:d*.,e
.e,*,b.,e,*,f.,e
e,:..,*,b.d*,*:.
b*,.,b*.,d,.:,f*
.e,f,b.,e,*,f.,e
f,b.d,*,b.d*,b.,
bd:*d*:e*,bd*d,e
de,*,bd,e,f,fd,e
e,bd,*,bdd*,*b.d
,f,db:*d,*,.b,f*
de,*,bd,e,f,fd,e
*,b.d,*,bd.*,b.d
'''