[texture]
name = "Ice"
description = "Semi-transparent ice block with varying opacity levels"
size = [16, 16]

[palette]
"." = "#E8F4FF99"  # Light ice blue (232, 244, 255, 153) - 60% opacity
"," = "#F0F8FFCC"  # Very light ice (240, 248, 255, 204) - 80% opacity
":" = "#D0E8FF66"  # Medium ice blue (208, 232, 255, 102) - 40% opacity
"*" = "#F8FCFFE6"  # Bright ice (248, 252, 255, 230) - 90% opacity
"#" = "#C0E0FF4D"  # Dark ice (192, 224, 255, 77) - 30% opacity
"~" = "#E0F0FF1A"  # Very transparent ice (224, 240, 255, 26) - 10% opacity

[pixels]
data = '''
*,:.~*,:~.,:,*:.
,:*,.~#.,*,.:,.*
.#,*,:~,*,*,:.,#
*,:..,*,:.~*,:.,
,.:*.*:#*,:.*.,#
.#,*,:.,:~*,:.,#
#,:.~,*,:..,*,*.
,*,.,:*~,*,.:,**
.#,*,:.,:,*,:.,#
*,:..,*,:.~*,:.,
,.:*.*:#*,:.*.,#
.#,*,:.,:~*,:.,#
#,:.~,*,:..,*,*.
,*,.,:*~,*,.:,**
.#,*,:.,:,*,:.,#
*,:..,*,:.~*,:.,
'''