[texture]
name = "Ice"
description = "Semi-transparent ice block with varying opacity levels"
size = [16, 16]

[palette]
"." = "#E8F4FF"  # Light ice blue (232, 244, 255)
"," = "#F0F8FF"  # Very light ice (240, 248, 255)
":" = "#D0E8FF"  # Medium ice blue (208, 232, 255)
"*" = "#F8FCFF"  # Bright ice (248, 252, 255)
"#" = "#C0E0FF"  # Dark ice (192, 224, 255)
"~" = "#E0F0FF"  # Very light ice (224, 240, 255)

[pixels]
data = '''
*,:.~*,:~.,:,*:.
,:*,.~#.,*,.:,.*
.#,*,:~,*,*,:.,#
*,:..,*,:.~*,:.,
,.:*.*:#*,:.*.,#
.#,*,:.,:~*,:.,#
#,:.~,*,:..,*,*.
,*,.,:*~,*,.:,**
.#,*,:.,:,*,:.,#
*,:..,*,:.~*,:.,
,.:*.*:#*,:.*.,#
.#,*,:.,:~*,:.,#
#,:.~,*,:..,*,*.
,*,.,:*~,*,.:,**
.#,*,:.,:,*,:.,#
*,:..,*,:.~*,:.,
'''