[texture]
name = "Leaves"
description = "Detailed leaf pattern with varying greens and transparency"
size = [16, 16]

[palette]
"." = "#4A7C2A"   # Base leaf green (74, 124, 42)
"," = "#5C9C3A"   # Light leaf green (92, 156, 58)
":" = "#3A5C1A"   # Dark leaf green (58, 92, 26)
"*" = "#6AAA4A"   # Bright leaf green (106, 170, 74)
"#" = "#2A4C0A"   # Very dark leaf green (42, 76, 10)
"_" = "#4A7C2A"   # Semi-transparent leaf green

[pixels]
data = '''
*,_:.*,_:.,*,*_.
_:*,.:#.,*,.:,.*
.#,*,:.,*,*,:.,#
*,_..*,:..*,:.,_
,.:*.*:#*,:.*._#
_#,*,:.,:,*,:.,#
#,_..*,:..*,*_._
,*,._:*.,*,.:,**
.#,*,:._:,*,:.,#
*,_..*,:..*,:.,_
,.:*.*:#*,:.*._#
_#,*,:.,:,*,:.,#
#,_..*,:..*,*_._
,*,._:*.,*,.:,**
.#,*,:._:,*,:.,#
*,_..*,:..*,:.,_
'''