[texture]
name = "Leaves"
description = "Detailed leaf pattern with varying greens and transparency"
size = [16, 16]

[palette]
"." = "#4A7C2AF0"   # Base leaf green (74, 124, 42, 240) - 94% opacity
"," = "#5C9C3AF5"   # Light leaf green (92, 156, 58, 245) - 96% opacity
":" = "#3A5C1AEB"   # Dark leaf green (58, 92, 26, 235) - 92% opacity
"*" = "#6AAA4AFF"   # Bright leaf green (106, 170, 74, 255) - 100% opacity
"#" = "#2A4C0AE6"   # Very dark leaf green (42, 76, 10, 230) - 90% opacity
"_" = "#4A7C2AE6"   # Semi-transparent leaf green instead of fully transparent

[pixels]
data = '''
*,_:.*,_:.,*,*_.
_:*,.:#.,*,.:,.*
.#,*,:.,*,*,:.,#
*,_..*,:..*,:.,_
,.:*.*:#*,:.*._#
_#,*,:.,:,*,:.,#
#,_..*,:..*,*_._
,*,._:*.,*,.:,**
.#,*,:._:,*,:.,#
*,_..*,:..*,:.,_
,.:*.*:#*,:.*._#
_#,*,:.,:,*,:.,#
#,_..*,:..*,*_._
,*,._:*.,*,.:,**
.#,*,:._:,*,:.,#
*,_..*,:..*,:.,_
'''