[texture]
name = "Planks"
description = "Wooden planks with horizontal grain"
size = [16, 16]

[palette]
"." = "#D4AA7D"  # Base plank brown (212, 170, 125)
"," = "#E8BE91"  # Light plank brown (232, 190, 145)
":" = "#C0966A"  # Dark plank brown (192, 150, 106)
"*" = "#DCB285"  # Medium plank brown (220, 178, 133)
"#" = "#AC8257"  # Very dark plank brown (172, 130, 87)

[pixels]
data = '''
.,*:.,*:.,*:.,*:
################
.,*:.,*:.,*:.,*:
.,*:.,*:.,*:.,*:
,,,,,,,,,,,,,,,,
.,*:.,*:.,*:.,*:
.,*:.,*:.,*:.,*:
################
.,*:.,*:.,*:.,*:
.,*:.,*:.,*:.,*:
,,,,,,,,,,,,,,,,
.,*:.,*:.,*:.,*:
.,*:.,*:.,*:.,*:
################
.,*:.,*:.,*:.,*:
.,*:.,*:.,*:.,*:
'''