[texture]
name = "Sand"
description = "Sandy beach/desert block texture"
size = [16, 16]

[palette]
"." = "#F4E4B8"  # Base sand (244, 228, 184)
"," = "#FFEFCC"  # Light sand (255, 239, 204)
":" = "#E0D0A4"  # Dark sand (224, 208, 164)
"*" = "#F8E8BC"  # Bright sand (248, 232, 188)
"#" = "#CCC090"  # Very dark sand (204, 192, 144)

[pixels]
data = '''
*,:..*,:..,:,*:.
,:*,.:##.,*,.:.*
.#,*,:.,*,*,:.,#
*,:..,*,:..*,:.,
,.:*.*:#*,:.*.,#
.#,*,:.,:,*,:.,#
#,:..,*,:..*,*:.
,*,.,:*.,*,.:,**
.#,*,:.,:,*,:.,#
*,:..,*,:..*,:.,
,.:*.*:#*,:.*.,#
.#,*,:.,:,*,:.,#
#,:..,*,:..*,*:.
,*,.,:*.,*,.:,**
.#,*,:.,:,*,:.,#
*,:..,*,:..*,:.,
'''