[texture]
name = "Snow"
description = "Clean white snow with subtle variations"
size = [16, 16]

[palette]
"." = "#FFFFFF"  # Pure white (255, 255, 255)
"," = "#F0F0F5"  # Light blue-white (240, 240, 245)
":" = "#E8E8ED"  # Slightly darker white (232, 232, 237)
"*" = "#F8F8FF"  # Bright white (248, 248, 255)
"#" = "#D8D8DD"  # Shadow white (216, 216, 221)

[pixels]
data = '''
*,:..*,:..,:,*:.
,:*,.:##.,*,.:.*
.#,*,:.,*,*,:.,#
*,:..,*,:..*,:.,
,.:*.*:#*,:.*.,#
.#,*,:.,:,*,:.,#
#,:..,*,:..*,*:.
,*,.,:*.,*,.:,**
.#,*,:.,:,*,:.,#
*,:..,*,:..*,:.,
,.:*.*:#*,:.*.,#
.#,*,:.,:,*,:.,#
#,:..,*,:..*,*:.
,*,.,:*.,*,.:,**
.#,*,:.,:,*,:.,#
*,:..,*,:..*,:.,
'''