[texture]
name = "Stone"
description = "A basic stone block with gray variations"
size = [16, 16]

[palette]
"." = "#787878"  # Base gray (120, 120, 120)
"," = "#888888"  # Light gray (136, 136, 136) - reduced from 150
":" = "#6E6E6E"  # Dark gray (110, 110, 110) - increased from 100
"*" = "#808086"  # Blue-tinted gray (128, 128, 134) - more subtle
"#" = "#686868"  # Very dark gray (104, 104, 104) - increased from 90

[pixels]
data = '''
.,:..,*,:..,*,:.
,*,.,:.,*,.,:.,*
.:,.,:.,:,.,:.,:
*,:..,*,:..,*,:.
,.,:.*,:.,*,.,:#
.:,*,:.,:,*,:.,:
#,:..,*,:..,*,:.
,*,.,:.,*,.,:.,*
.:,.,:.,:,.,:.,:
*,:..,*,:..,*,:.
,.,:.*,:.,*,.,:#
.:,*,:.,:,*,:.,:
#,:..,*,:..,*,:.
,*,.,:.,*,.,:.,*
.:,.,:.,:,.,:.,:
*,:..,*,:..,*,:.
'''