[texture]
name = "Water"
description = "Animated blue water texture"
size = [16, 16]

[palette]
"." = "#4A8FC8C0"  # Base water blue (74, 143, 200, 192) - 75% opacity
"," = "#5CA0D8D9"  # Light water blue (92, 160, 216, 217) - 85% opacity
":" = "#3A7FB8A6"  # Dark water blue (58, 127, 184, 166) - 65% opacity
"*" = "#6AB0E8E6"  # Bright water blue (106, 176, 232, 230) - 90% opacity
"#" = "#2A6FA88C"  # Very dark water blue (42, 111, 168, 140) - 55% opacity

[pixels]
data = '''
*,:..*,:..,:,*:.
,:*,.:##.,*,.:.*
.#,*,:.,*,*,:.,#
*,:..,*,:..*,:.,
,.:*.*:#*,:.*.,#
.#,*,:.,:,*,:.,#
#,:..,*,:..*,*:.
,*,.,:*.,*,.:,**
.#,*,:.,:,*,:.,#
*,:..,*,:..*,:.,
,.:*.*:#*,:.*.,#
.#,*,:.,:,*,:.,#
#,:..,*,:..*,*:.
,*,.,:*.,*,.:,**
.#,*,:.,:,*,:.,#
*,:..,*,:..*,:.,
'''