[texture]
name = "Water"
description = "Animated blue water texture"
size = [16, 16]

[palette]
"." = "#4A8FC8"  # Base water blue (74, 143, 200)
"," = "#5CA0D8"  # Light water blue (92, 160, 216)
":" = "#3A7FB8"  # Dark water blue (58, 127, 184)
"*" = "#6AB0E8"  # Bright water blue (106, 176, 232)
"#" = "#2A6FA8"  # Very dark water blue (42, 111, 168)

[pixels]
data = '''
*,:..*,:..,:,*:.
,:*,.:##.,*,.:.*
.#,*,:.,*,*,:.,#
*,:..,*,:..*,:.,
,.:*.*:#*,:.*.,#
.#,*,:.,:,*,:.,#
#,:..,*,:..*,*:.
,*,.,:*.,*,.:,**
.#,*,:.,:,*,:.,#
*,:..,*,:..*,:.,
,.:*.*:#*,:.*.,#
.#,*,:.,:,*,:.,#
#,:..,*,:..*,*:.
,*,.,:*.,*,.:,**
.#,*,:.,:,*,:.,#
*,:..,*,:..*,:.,
'''