[texture]
name = "Wood Side"
description = "Vertical wood grain pattern for log sides"
size = [16, 16]

[palette]
"." = "#8C5A2B"  # Base wood brown (140, 90, 43)
"," = "#A0632D"  # Light wood brown (160, 99, 45)
":" = "#6D4423"  # Dark wood brown (109, 68, 35)
"*" = "#996633"  # Medium wood brown (153, 102, 51)
"#" = "#5D3A1A"  # Very dark wood brown (93, 58, 26)

[pixels]
data = '''
.,*:.,*:.,*:.,*:
.,*:.,*:.,*:.,*:
*,:*.:,*.:,*.:,*
.,*:.,*:.,*:.,*:
.,*:.,*:.,*:.,*:
#,#:#,#:#,#:#,#:
.,*:.,*:.,*:.,*:
.,*:.,*:.,*:.,*:
*,:*.:,*.:,*.:,*
.,*:.,*:.,*:.,*:
.,*:.,*:.,*:.,*:
#,#:#,#:#,#:#,#:
.,*:.,*:.,*:.,*:
.,*:.,*:.,*:.,*:
*,:*.:,*.:,*.:,*
.,*:.,*:.,*:.,*:
'''